In [43]:
import numpy as np
from matrix import *

In [57]:
A = rand_matrix(3,3)
B = rand_matrix(3,3)
np_A = np.array(A)
np_B = np.array(B)


print_matrix(operation(A, B, '*'))
print_matrix(dot(A, B))

print(np_A.dot(np_B))


56 3 30 
45 35 27 
49 32 9 
125 46 50 
166 76 55 
191 83 68 
[[125  46  50]
 [166  76  55]
 [191  83  68]]
